version: '3.7'

services:
  service_db_local:
    image: mysql:5.7
    restart: always
    env_file:
      - env_files/mysql_local.env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}",  "ping", "-h", "localhost" ]
      interval: 3s
      timeout: 5s
      retries: 10
    volumes:
      - service_db_local:/var/lib/mysql

  app:
    build:
      context: .
    ports:
      - "80:80"
    env_file:
      - env_files/mysql_local.env
      - env_files/app_settings_local.env
    volumes:
      - ./app:/app
    depends_on:
      service_db_local:
        condition: service_healthy
    links:
      - service_db_local
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:80"

volumes:
  service_db_local:
      
      